### PR TITLE
Widen ember-modifier versions to support v4 (and add ember-auto-import v2 dependency)

### PR DESCRIPTION
**Pull request by SergeAstapov**
Closes #131 and #132

### CODE REVIEW

**Comment by SergeAstapov** [comment]
supersedes #131

**Comment by jelhan** [comment]
@SergeAstapov Thanks a lot for picking this one up. Would be great if you could add an ember try scenario for ember-modifier v3 to ensure that we actually have test coverage for both.

I think it should look this this:

```js
      {
        name: 'ember-modifier-v3',
        npm: {
          devDependencies: {
            'ember-modifier': '^3.2.7',
          },
        },
      },
```

Additionally it needs to be added to GitHub CI workflow to actually run it in CI. https://github.com/jelhan/ember-style-modifier/blob/ed5a86b569adf171a4084b03e408b5c37b2db9a0/.github/workflows/ci.yml#L58-L69

**Comment by jelhan** [comment]
Seems as we need to add `ember-auto-import` v2 as well. CI is failing with this error:

> ember-style-modifier needs to depend on ember-auto-import in order to use ember-modifier

**Comment by jelhan** [comment]
As we need to add a dependency to `ember-auto-import`, this is a breaking change:

> addons that upgrade to ember-auto-import 2.0 should do their own semver major releases, and document that they now require ember-auto-import 2.0 in the app. This implies that semver major releases are needed recursively up the dependency chain if an addon is using an addon that upgrades to ember-auto-import 2.0.
>
> https://github.com/ef4/ember-auto-import/blob/7db23cde28984353700658ced0d0b7a388389f76/docs/upgrade-guide-2.0.md

I missed adding that dependency before releasing `v1.0.0`. :cry:

**Comment by SergeAstapov** [comment]
> As we need to add a dependency to `ember-auto-import`, this is a breaking change

sounds like good time for V2 addon conversion :)

**Comment by jelhan** [comment]
> > As we need to add a dependency to `ember-auto-import`, this is a breaking change
> 
> sounds like good time for V2 addon conversion :)

That could be done in a follow-up PR. After adding `ember-auto-import@v2` as a dependency, that would be an implementation detail.

**Comment by SergeAstapov** [comment]
CI is now green per https://github.com/SergeAstapov/ember-style-modifier/pull/2/checks

**Comment by jelhan** [comment]
Thanks a lot for working on this one! I have just released it as [v2.0.0](https://github.com/jelhan/ember-style-modifier/releases/tag/v2.0.0).

**Pull request merged**
